app = "moviesList"

[build]
  builder = "paketobuildpacks/builder:full"

[[services]]
  internal_port = 8080
  external_port = 80
  [services.concurrency]
    type = "requests"
    soft_limit = 25
    hard_limit = 50
  [services.http_checks]
    path = "/"
    interval = "15s"
    timeout = "2s"
